<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-UUTKFR9P" ignored="0" name="test1" tests="8" failures="3" timestamp="2020-11-20T19:40:01 CST" time="430.023" errors="0">
  <testcase name="demo1" time="22.048" classname="com.webtest.demo.BaseInformation"/>
  <testcase name="demo1" time="40.512" classname="com.webtest.demo.UserSet">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="2">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 2
at com.webtest.core.BaseTest.getExcel(BaseTest.java:129)
at com.webtest.demo.UserSet.demo1(UserSet.java:36)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase name="demo2" time="31.562" classname="com.webtest.demo.MoneySet"/>
  <testcase name="demo3" time="46.414" classname="com.webtest.demo.PaySet">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.webtest.core.WebDriverEngine.getText(WebDriverEngine.java:185)
at com.webtest.demo.PaySet.demo3(PaySet.java:66)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- demo3 -->
  <testcase name="demo3" time="21.697" classname="com.webtest.demo.DeliverySet">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.webtest.demo.DeliverySet.demo3(DeliverySet.java:73)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- demo3 -->
  <testcase name="demo5" time="63.719" classname="com.webtest.demo.MessageSet"/>
  <testcase name="demo6" time="31.917" classname="com.webtest.demo.AreaSet"/>
  <testcase name="demo2" time="26.96" classname="com.webtest.demo.AdminSet"/>
</testsuite> <!-- test1 -->
