<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-5BQ8UDAV" failures="0" tests="5" name="com.webtest.demo.Admin_CMSManagement_AddText" time="0.016" errors="1" timestamp="2020-11-27T15:37:46 CST" skipped="4">
  <testcase classname="com.webtest.demo.Admin_CMSManagement_AddText" name="loginFirst" time="0.016">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.webtest.demo.Admin_CMSManagement_AddText.loginFirst(Admin_CMSManagement_AddText.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginFirst -->
  <system-out/>
  <testcase classname="com.webtest.demo.Admin_CMSManagement_AddText" name="addAtrticle1" time="0.000">
    <skipped/>
  </testcase> <!-- addAtrticle1 -->
  <system-out/>
  <testcase classname="com.webtest.demo.Admin_CMSManagement_AddText" name="addAtrticle2" time="0.000">
    <skipped/>
  </testcase> <!-- addAtrticle2 -->
  <system-out/>
  <testcase classname="com.webtest.demo.Admin_CMSManagement_AddText" name="addAtrticle3" time="0.000">
    <skipped/>
  </testcase> <!-- addAtrticle3 -->
  <system-out/>
  <testcase classname="com.webtest.demo.Admin_CMSManagement_AddText" name="addAtrticle4" time="0.000">
    <skipped/>
  </testcase> <!-- addAtrticle4 -->
  <system-out/>
</testsuite> <!-- com.webtest.demo.Admin_CMSManagement_AddText -->
